### PR TITLE
Fix gpg signing and encription

### PR DESCRIPTION
**Pull request by compuguy**
The current gpg plugin doesn't create properly signed or encrypted changes. These fixes from @Stankec should fix it.

### CODE REVIEW

**Comment by eelcocramer** [comment]
Will this be merged?

**Comment by Aggamemnon** [comment]
+1 happy to test.

**Comment by RicoLaaa** [comment]
any updates on this?

**Comment by stankec** [comment]
Guess merge conflicts should be resolved first.
I'd be glad if somebody could do that, otherwise, I can try to do it over the weekend. But no guarantees.

**Comment by RicoLaaa** [comment]
@stankec did you had a chance to look at it?

**Comment by stankec** [comment]
@RicoLaaa I did take a look and tried to merge with the upstream but noticed that the change wasn't insignificant and that I need more time. Sadly I forgot about this quite a few times and have been rather busy.

**Comment by KodaKoder** [comment]
Interesting I guess one of the major issue is that the plugin does not encrypt plain text messages
let me know if you need asistance

**Comment by RicoLaaa** [comment]
...monthly check... any news?
Installed last update v7 (which actually shows as v4 in Airmail)... but it doesn't seem to solve anything.

**Comment by stankec** [comment]
Hm... I guess I'll have some time tomorrow. I'll try to do it then.

**Comment by stankec** [comment]
Started working on it today. I think I'll be with it by friday.

**Comment by RicoLaaa** [comment]
Great news!

**Comment by AntonioMeireles** [comment]
@stankec - that would be awesome! We're all crossing fingers :-)

**Comment by stankec** [comment]
Sorry got a bit of a snag the last two days. I’ll try to finish it tomorrow

**Comment by shime** [comment]
I started working on this, should be done by the end of the weekend. Fingers crossed.

**Comment by stankec** [comment]
I've resolved the conflicts and fixed key lookup to only use trusted keys.
If somebody needs the old codebase it's still available [here](https://github.com/stankec/AirmailPlugIn-Framework/tree/feature/fix_message_encryption).

@RicoLaaa  @AntonioMeireles  the issues should now be resolved. If you have the time I'd appreciate if you test this build out.

**Comment by RicoLaaa** [comment]
@stankec i'll be happy to test if you have a compiled version somewhere...

**Comment by stankec** [comment]
The file's MD5 hash is `4d7efe3d357b4a2ac7f79f4781ad6438` 
You can download it here: [AMPGpg.zip](https://github.com/Airmail/AirmailPlugIn-Framework/files/1471146/AMPGpg.zip)

I can also send you a signed ZIP if you want to verify the file was sent by me.

**Comment by stankec** [comment]
@RicoLaaa  sorry, forgot to mention you in the last comment.

**Comment by RicoLaaa** [comment]
@stankec thanks, I just sent you an email.

**Comment by RicoLaaa** [comment]
Seems to be working fine so far, tested on just signed and encrypted mails! Thanks @stankec !

Any feedback from other testers?

**Comment by compuguy** [comment]
@RicoLaaa @stankec Looks like this works.

**Comment by riordan** [comment]
I've been having an issue where Airmail will freeze up when it encounters a signed thread. Will this PR fix this problem as well?

**Comment by stankec** [comment]
@riordan  Hi! 👋 

I'm not sure if this PR will fix that issue. 
I personally use this version of the Plugin and I haven't experienced the issue you described (though the longest encrypted thread I have in my mailbox is only 30 messages long).

Also, try looking at your local GPG installation. While Airmail uses `libMacGPG` it in turn mostly does system calls to the local GPG installation (nearly completely circumventing `libgpg`).

I've had issues with Airmail freezing up while I was using a non-GUI pinentry program. Please make sure that you can use the `gpg` command through a terminal emulator, and that it prompts a GUI pinentry dialog.

Please feel free to test this version of the plugin out and report your finding. If you don't trust the provided `zip` file above you can always ping me via [email](mailto:hey@stanko.io) and I can send you a signed version.

Hope this cleared things up / helped you.

**Pull request merged**
