### PR TITLE
Fix double armor and signature recognition failure

### PR DESCRIPTION
**Pull request by shtirlic**

### CODE REVIEW

**Comment by wilfreddekok** [comment]
Good fix!

**Comment by dm4** [comment]
Anyone could merge this pull request and release it to http://support.airmailapp.com/post/95764147348/gpg-pgp-plugin ?

cc @Bloophub @KodaKoder @Omegaice @larrymcj @michiexile

**Comment by compuguy** [comment]
Would love this fix, plugin is currently useless in Airmail!

**Comment by dm4** [comment]
Thank you @KodaKoder for merging this PR!!!

**Comment by KodaKoder** [comment]
:)

**Comment by compuguy** [comment]
@KodaKoder Now we need a new release posted either here or in http://support.airmailapp.com/post/95764147348/gpg-pgp-plugin

**Pull request merged**
